### PR TITLE
feat: add container build here

### LINKED ISSUE #1: Store images in the ghcr.io container registry
With Docker sunsetting Free Team accounts we're moving over to ghcr.io for the time being.

### PR DESCRIPTION
**Pull request by esolitos**
## What

- fixes #1
- Updates to the latest version and ensures automatic weekly updates

### CODE REVIEW

**Comment by esolitos** [comment]
@eiriksm We have a very outdated version of [nymediaas/chrome-headless](https://hub.docker.com/r/nymediaas/chrome-headless) on docker hub _(>3y old, it can walk and talk at this point)_, and AFAIK this is manually pushed.

This wants to make the process automated.

**Review by eiriksm — APPROVED** [review]
I would like to move to not using this base image though. I have done some efforts from time to time to check if we can change this, but it's going to break for sure.

That being said, I guess this just pushes it to ghcr so that would be fine. So no breakage in sight if we just start to do that

**Comment by esolitos** [comment]
> I would like to move to not using this base image though. 

Care to expand a bit on this?

**Comment by eiriksm** [comment]
My reason was: It seems to be unmaintained and out of date.

BUT

I was going to the docker hub page to get some verification of that claim, and it's actually not at all :thinking: I guess it was at some point but then resurrected?

**Comment by esolitos** [comment]
Yeah, I looked at the github and it looked relatively alive. 😄 
But then again, they say the latest version is 100, while chrome is now at 120.. so.. Yeah, not the best. Perhaps I can replace the base image with the actual installation steps, they're very basic anyway.

Well, for now I mostly needed to test it with for this PR: https://github.com/nymedia/akademika_d8/pull/4433

**Pull request merged**
